
version: "3.8"

services:
  postgres:
    container_name: todo_db
    environment:
      POSTGRES_PASSWORD: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-todos
    command: redis-server

  app:
    container_name: todo
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    read_only: false
    restart: always
    entrypoint: ./entrypoints/docker-entrypoint.sh

  app-migrations:
    container_name: todo-migrations
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
    volumes:
      - .:/app
    env_file: .env
    read_only: false
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/setup-db.sh

  mailcatcher:
    image: yappabe/mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
  
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app
      - postgres
      - redis
    volumes:
      - .:/app
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: chmod +x ./entrypoints/sidekiq-entrypoint.sh

volumes:
  postgres-data:
  app:
  redis:

networks:
  app: